### ISSUE TITLE
Is there a way to dynamically pass in tags to be executed?

### ISSUE THREAD

**Issue by ddelponte** [dkowis/cucumber-jvm-groovy-example#3]
For example, I have this in my `build.gradle` file:

```
tags = ["@COMPLETED", "~@ignore"]
```

This will run all features and/or scenarios that are tagged as `COMPLETED` but not `ignore`.

If I want to run all tests tagged as `awesome`, I would modify that line to be:

```
tags = ["@awesome"]
```

How can I accomplish this same thing but at the command line or with environmental variables (or some other way)?

I want it to be dynamic so, for instance, I could create a Jenkins job that would run only the tests tagged in the Jenkins job.  This allows flexibility without having to modify the code.

**Comment by dkowis** [comment]
Yes, but it's a gradle thing, not specific to this project: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties

Gradle lets you write groovy code, and so you can do almost anything you want. http://stackoverflow.com/questions/11696521/how-to-pass-arguments-from-command-line-to-gradle is also a useful example.

**Comment by ddelponte** [comment]
Thank-you!
