### ISSUE TITLE
Where did you found info about using the World hook

### ISSUE THREAD

**Issue by silver-mx** [dkowis/cucumber-jvm-groovy-example#4]
Hi! I am just curious about the use of the World hook in your example. I have been trying to find a good source but all seems very shallow. I would appreciate if you can point out something. Thanks!

**Comment by dkowis** [comment]
I'll have to look at it again. I haven't built this in a while. When I get a chance I'll try to describe it more. 

On September 11, 2018 4:01:55 PM CDT, "Diego Núñez Silva" <notifications@github.com> wrote:
>Hi! I am just curious about the use of the World hook in your example.
>I have been trying to find a good source but all seems very shallow. I
>would appreciate if you can point out something. Thanks!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dkowis/cucumber-jvm-groovy-example/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dkowis** [comment]
Hm... I don't remember where I found info about the World hook. It may just be there to allow you to add functionality to the scope of all the Given/When/Then methods.

https://github.com/cucumber/cucumber-jvm-groovy

I found it in the source code there. Basically you can use the `World()` DSL to add anything that you want to be available in all of the given/when/then blocks.

**Comment by silver-mx** [comment]
Thanks @dkowis for the information. I just found in "The cucumber for Java Book" an appendix  that describes a bit cucumber in other JVM languages (Groovy and Scala) and describes a bit the Groovy World, which supports what you say and show in the example. Thanks again for checking!
